### PR TITLE
add -std=gnu++11 to CXX_FLAGS

### PR DESCRIPTION
**Pull request by rgrover**
otherwise minar won't build on POSIX

@bogdanm @autopulated

### CODE REVIEW

**Comment by bogdanm** [comment]
+1

**Comment by bogdanm** [comment]
(but note that this might affect code that uses this target, for example mbed-linux-client)

**Comment by autopulated** [comment]
cc @ARMmbed/mbed-client, does mbed-client build with C++11 on Linux?

**Comment by yogpan01** [comment]
Can this change be done at component itself (whichever needs it) through its custom CMakeList.txt ?

**Comment by autopulated** [comment]
It can be overridden there, but in general we're now compiling things as C++11, so this should probably be the default.

Also, we should probably be using CMAKE_CXX_STANDARD rather than setting this flag directly.

**Comment by rgrover** [comment]
@autopulated @bogdanm could you please merge this? It will enable the use of minar/utest on POSIX.

**Comment by autopulated** [comment]
@yogpan01 if you're OK with this, then I'll merge.

**Comment by yogpan01** [comment]
I am fine with this as long as its not conflicting with Q1 release :)

**Comment by autopulated** [comment]
Would it conflict with the Q1 release?

**Comment by rgrover** [comment]
@bogdanm: do you see any reason for this change to interfere with the Q1 release?

**Comment by yogpan01** [comment]
I think this can be merged, should not conflict with release anymore.

**Pull request merged**
